# Use an official Node.js image
FROM node:23-slim

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy app source code
COPY . .

# Expose the port your app runs on
EXPOSE 4567

# Start the app
CMD ["node", "express.js"]
