name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure-as-code
         
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infrastructure-as-code

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary
        working-directory: ./infrastructure-as-code

      - name: Terraform Show
        run: terraform show -no-color tfplan.binary
        working-directory: ./infrastructure-as-code
